name: nine_patch_common
description: Common code for dealing with nine-patch images.
version: 1.0.0
repository: https://github.com/bramp/nine_patch

environment:
  sdk: ^3.0.6

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
