name: nine_patch
description: Flutter package for displaying nine-patch images.
version: 1.0.0
repository: https://github.com/bramp/nine_patch

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  nine_patch_common: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
